package com.example.shiftalarmmvp.recovery

internal fun testRecoveryStrings(): RecoveryStrings {
    return RecoveryStrings(
        home = HomeReliabilityStrings(
            statusActionNeeded = "Action needed",
            statusCheckNeeded = "Check needed",
            statusSafe = "Safe",
            reasonRecoveryNeedsReschedule = "Recovery detected alarms that need another scheduling pass.",
            reasonSelfTestFailed = "The most recent self-test failed.",
            actionOpenCenter = "Open center",
            actionRefreshStatus = "Refresh status",
            actionRunSelfTest = "Run self-test",
            actionRecheck = "Recheck",
            followUpScheduled = "A self-test is scheduled and waiting to fire.",
            followUpTriggered = "The self-test alarm fired. Confirm the result.",
            followUpUncertain = "A recent self-test was not confirmed. Run it again.",
            followUpCanceled = "The self-test was canceled. Run it again.",
            followUpDefault = "Run a self-test to verify alarm delivery.",
            reasonNightlyIssue = "A nightly reliability check reported issues.",
            reasonSafe = "Alarm reliability checks are healthy."
        ),
        setup = ReliabilitySetupStrings(
            statusActionNeeded = "Action needed",
            exactAlarmTitle = "Exact alarm permission",
            exactAlarmReadyStatus = "Exact alarm: ready",
            exactAlarmPendingStatus = "Exact alarm: required",
            exactAlarmDetail = "Android 12+ needs exact alarm access for guaranteed wake alarms.",
            exactAlarmAction = "Enable exact alarms",
            notificationTitle = "Notification permission",
            notificationReadyStatus = "Notifications: allowed",
            notificationPendingStatus = "Notifications: required",
            notificationDetail = "Notifications are required for alarm state feedback.",
            notificationAction = "Enable notifications",
            alarmRegistrationTitle = "Next alarm registration",
            alarmRegistrationReadyStatus = "Next alarm: registered",
            alarmRegistrationPendingStatus = "Next alarm: needs check",
            alarmRegistrationDetail = "The next wake alarm is not visible in the system alarm registry.",
            alarmRegistrationAction = "Reschedule alarms",
            batteryTitle = "Battery protection",
            batteryReadyStatus = "Battery: exempted",
            batteryPendingStatus = "Battery: guidance recommended",
            batteryDetail = "Battery restrictions can suppress alarm delivery.",
            batteryAction = "Open battery settings",
            summaryNoExtraSteps = "No extra setup steps are required.",
            summaryAllReady = "Permissions and protections are ready.",
            summaryProgressFormat = "Setup progress %1\$d/%2\$d complete - continue with %3\$s"
        ),
        overview = ReliabilityOverviewStrings(
            watchdogEmpty = "No watchdog history",
            restorePostCheckEmpty = "No restore post-check history",
            recoveryEmpty = "No recovery record",
            latestRecoveryActionEmpty = "No recent recovery action",
            selfTestEmpty = "No self-test history",
            nightlyCheckEmpty = "No nightly check history"
        ),
        restorePostCheck = RestorePostCheckStrings(
            homeReasonPending = "A restored backup still needs a reliability recheck.",
            linePendingFormat = "%1\$s restore completed - reliability recheck required.",
            lineCompletedFormat = "%1\$s restore recheck completed."
        ),
        nightlyCheck = NightlyCheckStrings(
            stateCheckNeeded = "Check needed",
            stateGood = "Good",
            bannerFormat = "Nightly check %1\$s - %2\$s - %3\$s",
            summaryNone = "No nightly check history"
        ),
        reschedule = RescheduleRecoveryStrings(
            outcomeNoActive = "No active alarms",
            outcomePartial = "Partial recovery",
            outcomeDegraded = "Fallback scheduled",
            outcomeFull = "Recovered",
            countZero = "0/0",
            countExactFormat = "exact %1\$d / total %2\$d",
            countFallbackFormat = "exact %1\$d / fallback %2\$d / total %3\$d",
            countBlockedFormat = "scheduled %1\$d/%2\$d / fallback %3\$d / blocked %4\$d",
            homeSummaryFormat = "Recovery %1\$s | %2\$s | %3\$s (%4\$s)",
            oneLineFullFormat = "%1\$s %2\$s restored %3\$s.",
            oneLineDegradedFormat = "%1\$s %2\$s kept %3\$s with fallback scheduling.",
            oneLinePartialFormat = "%1\$s %2\$s restored only %3\$s.",
            oneLineNoActiveFormat = "%1\$s %2\$s found no active alarms.",
            actionBoot = "Boot",
            actionTimezoneChanged = "Timezone changed",
            actionTimeChanged = "Time changed",
            actionDateChanged = "Date changed",
            actionAppUpdated = "App updated",
            actionExactPermissionGranted = "Exact permission granted",
            actionExactPermissionLost = "Exact permission lost",
            actionManual = "Manual reschedule",
            actionRestore = "Restore",
            actionStateChanged = "State changed",
            actionWithReasonFormat = "%1\$s - %2\$s",
            reasonExactPermissionDenied = "Exact permission denied",
            reasonExactSecurityException = "Exact alarm security exception",
            reasonPlatformFailure = "Platform scheduling failure",
            reasonNoNextTrigger = "No next trigger"
        ),
        selfTestStatus = SelfTestStatusStrings(
            statusNone = "No self-test history",
            statusScheduled = "Self-test scheduled",
            statusTriggered = "Self-test triggered",
            statusPassed = "Self-test passed",
            statusUncertain = "Self-test uncertain",
            statusFailed = "Self-test failed",
            statusCanceled = "Self-test canceled",
            detailNone = "None",
            homeSummaryFormat = "Self-test %1\$s - %2\$s"
        ),
        watchdog = AlarmWatchdogStrings(
            overviewEmpty = "No watchdog history",
            lineCleanFormat = "Watchdog checked clean at %1\$s",
            lineMissedFormat = "%1\$s watchdog detected a missed alarm for %2\$s (%3\$s).",
            lineSelfHealedFormat = "%1\$s watchdog re-scheduled %2\$s after a missed alarm (%3\$s).",
            lineCheckFailedFormat = "%1\$s watchdog could not verify alarm delivery.",
            homeReasonIncidentFormat = "A missed alarm incident was detected for %1\$s (%2\$s).",
            homeReasonCheckFailed = "The watchdog could not verify recent alarm delivery.",
            homeReasonClean = "Watchdog checks are clean.",
            inspectorIssueIncident = "Watchdog incident",
            notificationChannelName = "Missed alarm incidents",
            notificationChannelDescription = "Reports missed alarm incidents and self-healing actions.",
            notificationTitle = "Missed alarm incident detected",
            notificationTextFormat = "%1\$s may have been missed. Possible cause: %2\$s.",
            unknownAlarmLabel = "Unknown alarm",
            causeExactPermissionLost = "Exact permission lost",
            causeInexactFallbackDelay = "Inexact fallback delay",
            causeBatteryRestriction = "Battery restriction",
            causeRegistrationLoss = "Registration loss",
            causeUnknown = "Unknown cause"
        ),
        inspector = ReliabilityInspectorStrings(
            issueExactAlarmPermission = "Exact alarm permission",
            issueNotificationPermission = "Notification permission",
            issueSelfTestFailed = "Self-test failed",
            issueSelfTestRecheckRecommended = "Self-test recheck recommended",
            issueSelfTestCheckNeeded = "Self-test check needed",
            issueBatteryNotExempt = "Battery exemption missing",
            issueRecoveryPartial = "Partial recovery",
            issueRecoveryDegraded = "Fallback scheduling active",
            issueWatchdogIncident = "Watchdog incident",
            summaryReady = "Ready",
            summaryOverflowFormat = "%1\$s and %2\$d more"
        ),
        nightlyNotification = NightlyNotificationStrings(
            channelName = "Nightly check",
            channelDescription = "Checks alarm reliability before sleep.",
            notificationTitleCheckNeeded = "Nightly check: attention needed",
            notificationBigTextFormat = "%1\$s\nOpen the app to fix it."
        )
    )
}
